### ISSUE TITLE
온보딩, 저장, 폴더 추가 화면 QA 반영 

### ISSUE THREAD

**Issue by klmyoungyun** [mash-up-kr/Dorabangs_iOS#133]
### 이슈 설명
온보딩, 저장, 폴더 추가 화면 QA 반영 
### TODO
- [x] 온보딩 버튼 라인 색
- [x] 링크 저장 기사 제목 2줄
- [x] 입력한 텍스트가 없을 때 버튼 비활성화
- [x] 앱 아이콘
