### ISSUE TITLE
홈 작업

### ISSUE THREAD

**Issue by AhnSangHee** [mash-up-kr/Dorabangs_iOS#137]
### 이슈 설명
홈 작업

### TODO
- [x] 홈 배너 API 연동
- [x] 홈 배너 카드 눌렀을 때 동작
- [x] 스켈레톤 이슈 수정
