### ISSUE TITLE
디자인시스템에 컬러, 폰트 추가 및 프리뷰 구현

### ISSUE THREAD

**Issue by klmyoungyun** [mash-up-kr/Dorabangs_iOS#3]
### 이슈 설명
- 디자인시스템에 컬러(Extended Gray, Opacity, Alert)를 추가하고 프리뷰를 구현할게요.
- 디자인시스템에 폰트(NanumSquare Neo Variable)를 추가하고 프리뷰를 구현할게요

### TODO
- [x] 프리뷰 타겟 추가
- [x] 컬러(Extended Gray, Opacity, Alert) 추가 및 프리뷰 구현
- [x] 폰트(NanumSquare Neo variable)를 추가하고 프리뷰를 구현
